### ISSUE TITLE
Building against opencv 3 on OS X

### ISSUE THREAD

**Issue by jonathanhickford** [delmottea/libCMT#11]
I'm getting the error below when building on OS X Yosemite and using opencv-3.0.0 beta.

Is this due to a change between opencv 2.9 and 3?

error: no member named 'create' in 'cv::Algorithm'
    detector = cv::Algorithm::create<cv::FeatureDetector>(detectorType.c_str());

**Comment by delmottea** [comment]
yes, this is due to the change in the API between opencv 2.9 and 3.0.
I'll try to make it compatible when I have free time.
